/**
 * Master Conversion Map
 * =====================
 * Every entry here generates a dedicated SEO landing page.
 * Only verified, working backend conversions are included.
 */

// ─── File Conversions ────────────────────────────────────────────────

export const CONVERSION_MAP = [
  // ── Image ↔ Image ──────────────────────────────────────────────────
  {
    slug: 'jpg-to-png',
    from: 'JPG',
    to: 'PNG',
    fromExt: '.jpg',
    targetFormat: 'png',
    category: 'image',
    title: 'JPG to PNG Converter — Free Online | FileForge',
    description: 'Convert JPG images to PNG format with transparent background support. Fast, free, and secure. No signup required.',
    headline: 'Convert JPG to PNG',
    subtext: 'Transform your JPG photos into high-quality PNG images with transparency support.',
  },
  {
    slug: 'png-to-jpg',
    from: 'PNG',
    to: 'JPG',
    fromExt: '.png',
    targetFormat: 'jpg',
    category: 'image',
    title: 'PNG to JPG Converter — Free Online | FileForge',
    description: 'Convert PNG images to JPG format for smaller file sizes. Fast, free, and secure.',
    headline: 'Convert PNG to JPG',
    subtext: 'Reduce file size by converting PNG images to optimized JPG format.',
  },
  {
    slug: 'jpg-to-webp',
    from: 'JPG',
    to: 'WebP',
    fromExt: '.jpg',
    targetFormat: 'webp',
    category: 'image',
    title: 'JPG to WebP Converter — Free Online | FileForge',
    description: 'Convert JPG images to modern WebP format for faster web loading. Up to 30% smaller files.',
    headline: 'Convert JPG to WebP',
    subtext: 'Optimize your images for the web with Google\'s modern WebP format.',
  },
  {
    slug: 'webp-to-jpg',
    from: 'WebP',
    to: 'JPG',
    fromExt: '.webp',
    targetFormat: 'jpg',
    category: 'image',
    title: 'WebP to JPG Converter — Free Online | FileForge',
    description: 'Convert WebP images to universally compatible JPG format. Fast and free.',
    headline: 'Convert WebP to JPG',
    subtext: 'Make your WebP images universally compatible by converting to JPG.',
  },
  {
    slug: 'png-to-webp',
    from: 'PNG',
    to: 'WebP',
    fromExt: '.png',
    targetFormat: 'webp',
    category: 'image',
    title: 'PNG to WebP Converter — Free Online | FileForge',
    description: 'Convert PNG images to WebP for dramatically smaller file sizes while keeping quality.',
    headline: 'Convert PNG to WebP',
    subtext: 'Shrink your PNG images by up to 50% with lossless WebP conversion.',
  },
  {
    slug: 'webp-to-png',
    from: 'WebP',
    to: 'PNG',
    fromExt: '.webp',
    targetFormat: 'png',
    category: 'image',
    title: 'WebP to PNG Converter — Free Online | FileForge',
    description: 'Convert WebP images to PNG format with full transparency support.',
    headline: 'Convert WebP to PNG',
    subtext: 'Get full transparency and compatibility by converting WebP to PNG.',
  },
  {
    slug: 'jpeg-to-png',
    from: 'JPEG',
    to: 'PNG',
    fromExt: '.jpeg',
    targetFormat: 'png',
    category: 'image',
    title: 'JPEG to PNG Converter — Free Online | FileForge',
    description: 'Convert JPEG images to PNG format with lossless quality. No signup required.',
    headline: 'Convert JPEG to PNG',
    subtext: 'Upgrade your JPEG images to lossless PNG quality.',
  },
  {
    slug: 'jpeg-to-webp',
    from: 'JPEG',
    to: 'WebP',
    fromExt: '.jpeg',
    targetFormat: 'webp',
    category: 'image',
    title: 'JPEG to WebP Converter — Free Online | FileForge',
    description: 'Convert JPEG images to next-gen WebP format for faster websites.',
    headline: 'Convert JPEG to WebP',
    subtext: 'Modernize your images with blazing-fast WebP compression.',
  },
  {
    slug: 'webp-to-jpeg',
    from: 'WebP',
    to: 'JPEG',
    fromExt: '.webp',
    targetFormat: 'jpeg',
    category: 'image',
    title: 'WebP to JPEG Converter — Free Online | FileForge',
    description: 'Convert WebP images to widely supported JPEG format.',
    headline: 'Convert WebP to JPEG',
    subtext: 'Ensure maximum compatibility by converting to JPEG.',
  },

  // ── Video ↔ Video ──────────────────────────────────────────────────
  {
    slug: 'mp4-to-avi',
    from: 'MP4',
    to: 'AVI',
    fromExt: '.mp4',
    targetFormat: 'avi',
    category: 'video',
    title: 'MP4 to AVI Converter — Free Online | FileForge',
    description: 'Convert MP4 videos to AVI format for legacy device compatibility. Fast and secure.',
    headline: 'Convert MP4 to AVI',
    subtext: 'Make your videos compatible with older players and devices.',
  },
  {
    slug: 'avi-to-mp4',
    from: 'AVI',
    to: 'MP4',
    fromExt: '.avi',
    targetFormat: 'mp4',
    category: 'video',
    title: 'AVI to MP4 Converter — Free Online | FileForge',
    description: 'Convert AVI videos to modern MP4 format for smaller files and wider compatibility.',
    headline: 'Convert AVI to MP4',
    subtext: 'Modernize your videos with universally supported MP4 format.',
  },
  {
    slug: 'mp4-to-mov',
    from: 'MP4',
    to: 'MOV',
    fromExt: '.mp4',
    targetFormat: 'mov',
    category: 'video',
    title: 'MP4 to MOV Converter — Free Online | FileForge',
    description: 'Convert MP4 videos to Apple MOV format for Final Cut Pro and QuickTime.',
    headline: 'Convert MP4 to MOV',
    subtext: 'Perfect for Apple ecosystem — edit in Final Cut Pro or watch in QuickTime.',
  },
  {
    slug: 'mov-to-mp4',
    from: 'MOV',
    to: 'MP4',
    fromExt: '.mov',
    targetFormat: 'mp4',
    category: 'video',
    title: 'MOV to MP4 Converter — Free Online | FileForge',
    description: 'Convert Apple MOV videos to MP4 for universal playback on any device.',
    headline: 'Convert MOV to MP4',
    subtext: 'Share your Apple videos anywhere with universal MP4 format.',
  },
  {
    slug: 'mp4-to-gif',
    from: 'MP4',
    to: 'GIF',
    fromExt: '.mp4',
    targetFormat: 'gif',
    category: 'video',
    title: 'MP4 to GIF Converter — Free Online | FileForge',
    description: 'Create animated GIFs from MP4 videos. Perfect for memes and social media.',
    headline: 'Convert MP4 to GIF',
    subtext: 'Turn your video clips into shareable animated GIFs.',
  },
  {
    slug: 'avi-to-mov',
    from: 'AVI',
    to: 'MOV',
    fromExt: '.avi',
    targetFormat: 'mov',
    category: 'video',
    title: 'AVI to MOV Converter — Free Online | FileForge',
    description: 'Convert AVI videos to Apple MOV format for Mac compatibility.',
    headline: 'Convert AVI to MOV',
    subtext: 'Bring your AVI files into the Apple ecosystem.',
  },

  // ── Video → Audio ──────────────────────────────────────────────────
  {
    slug: 'mp4-to-mp3',
    from: 'MP4',
    to: 'MP3',
    fromExt: '.mp4',
    targetFormat: 'mp3',
    category: 'video',
    title: 'MP4 to MP3 Converter — Extract Audio Free | FileForge',
    description: 'Extract audio from MP4 videos and save as MP3. Perfect for podcasts and music.',
    headline: 'Extract Audio from MP4',
    subtext: 'Pull the audio track out of any video and save it as a high-quality MP3.',
  },
  {
    slug: 'mp4-to-wav',
    from: 'MP4',
    to: 'WAV',
    fromExt: '.mp4',
    targetFormat: 'wav',
    category: 'video',
    title: 'MP4 to WAV Converter — Extract Lossless Audio | FileForge',
    description: 'Extract lossless WAV audio from MP4 videos for professional editing.',
    headline: 'Extract Lossless Audio from MP4',
    subtext: 'Get studio-quality WAV audio from your video files.',
  },
  {
    slug: 'avi-to-mp3',
    from: 'AVI',
    to: 'MP3',
    fromExt: '.avi',
    targetFormat: 'mp3',
    category: 'video',
    title: 'AVI to MP3 Converter — Extract Audio Free | FileForge',
    description: 'Extract audio from AVI videos and convert to MP3 format.',
    headline: 'Extract Audio from AVI',
    subtext: 'Rip the audio from your AVI files into portable MP3 format.',
  },
  {
    slug: 'mov-to-mp3',
    from: 'MOV',
    to: 'MP3',
    fromExt: '.mov',
    targetFormat: 'mp3',
    category: 'video',
    title: 'MOV to MP3 Converter — Extract Audio Free | FileForge',
    description: 'Extract audio from Apple MOV videos and save as MP3.',
    headline: 'Extract Audio from MOV',
    subtext: 'Convert your QuickTime recordings into lightweight MP3 audio.',
  },

  // ── Audio ↔ Audio ──────────────────────────────────────────────────
  {
    slug: 'mp3-to-wav',
    from: 'MP3',
    to: 'WAV',
    fromExt: '.mp3',
    targetFormat: 'wav',
    category: 'audio',
    title: 'MP3 to WAV Converter — Free Online | FileForge',
    description: 'Convert MP3 audio to lossless WAV format for professional editing and mastering.',
    headline: 'Convert MP3 to WAV',
    subtext: 'Get uncompressed, studio-quality audio from your MP3 files.',
  },
  {
    slug: 'wav-to-mp3',
    from: 'WAV',
    to: 'MP3',
    fromExt: '.wav',
    targetFormat: 'mp3',
    category: 'audio',
    title: 'WAV to MP3 Converter — Free Online | FileForge',
    description: 'Compress WAV files to MP3 format for smaller size and easy sharing.',
    headline: 'Convert WAV to MP3',
    subtext: 'Shrink your audio files dramatically while keeping great sound quality.',
  },
  {
    slug: 'mp3-to-aac',
    from: 'MP3',
    to: 'AAC',
    fromExt: '.mp3',
    targetFormat: 'aac',
    category: 'audio',
    title: 'MP3 to AAC Converter — Free Online | FileForge',
    description: 'Convert MP3 to AAC for better audio quality at lower bitrates. Ideal for Apple devices.',
    headline: 'Convert MP3 to AAC',
    subtext: 'Upgrade to Apple\'s preferred audio format with superior compression.',
  },
  {
    slug: 'aac-to-mp3',
    from: 'AAC',
    to: 'MP3',
    fromExt: '.aac',
    targetFormat: 'mp3',
    category: 'audio',
    title: 'AAC to MP3 Converter — Free Online | FileForge',
    description: 'Convert AAC audio to universally compatible MP3 format.',
    headline: 'Convert AAC to MP3',
    subtext: 'Make your Apple audio files playable on any device.',
  },
  {
    slug: 'flac-to-mp3',
    from: 'FLAC',
    to: 'MP3',
    fromExt: '.flac',
    targetFormat: 'mp3',
    category: 'audio',
    title: 'FLAC to MP3 Converter — Free Online | FileForge',
    description: 'Convert lossless FLAC audio to compact MP3 for portable listening.',
    headline: 'Convert FLAC to MP3',
    subtext: 'Take your high-fidelity music on the go in portable MP3 format.',
  },
  {
    slug: 'wav-to-aac',
    from: 'WAV',
    to: 'AAC',
    fromExt: '.wav',
    targetFormat: 'aac',
    category: 'audio',
    title: 'WAV to AAC Converter — Free Online | FileForge',
    description: 'Convert WAV audio to efficient AAC format with minimal quality loss.',
    headline: 'Convert WAV to AAC',
    subtext: 'Compress your WAV files with Apple\'s superior AAC codec.',
  },

  // ── Document ───────────────────────────────────────────────────────
  {
    slug: 'pdf-to-docx',
    from: 'PDF',
    to: 'DOCX',
    fromExt: '.pdf',
    targetFormat: 'docx',
    category: 'document',
    title: 'PDF to Word Converter — Free Online | FileForge',
    description: 'Convert PDF documents to editable Word DOCX files. Preserves formatting and layout.',
    headline: 'Convert PDF to Word',
    subtext: 'Make your PDFs editable again — convert to Microsoft Word with layout preserved.',
  },
  {
    slug: 'pdf-to-jpg',
    from: 'PDF',
    to: 'JPG',
    fromExt: '.pdf',
    targetFormat: 'jpg',
    category: 'document',
    title: 'PDF to JPG Converter — Free Online | FileForge',
    description: 'Convert PDF pages to high-quality JPG images. Perfect for presentations and social media.',
    headline: 'Convert PDF to JPG',
    subtext: 'Turn your PDF pages into shareable JPG images instantly.',
  },
  {
    slug: 'pdf-to-png',
    from: 'PDF',
    to: 'PNG',
    fromExt: '.pdf',
    targetFormat: 'png',
    category: 'document',
    title: 'PDF to PNG Converter — Free Online | FileForge',
    description: 'Convert PDF pages to high-resolution PNG images with transparency support.',
    headline: 'Convert PDF to PNG',
    subtext: 'Export your PDFs as crystal-clear PNG images.',
  },
];

// ─── PDF Tools ───────────────────────────────────────────────────────

export const PDF_TOOLS = [
  {
    slug: 'merge',
    tool: 'merge',
    title: 'Merge PDF Files Online — Free | FileForge',
    description: 'Combine multiple PDF files into a single document. Upload up to 10 PDFs. Supports password-protected files.',
    headline: 'Merge PDF Files',
    subtext: 'Combine up to 10 PDF documents into one seamless file. Password support included.',
    icon: '📎',
    color: '#ef4444', // Red
  },
  {
    slug: 'split',
    tool: 'split',
    title: 'Split PDF Pages Online — Free | FileForge',
    description: 'Extract specific pages from a PDF document. Choose your page range and download instantly.',
    headline: 'Split PDF Pages',
    subtext: 'Extract exactly the pages you need from any PDF document.',
    icon: '✂️',
    color: '#f97316', // Orange
  },
  {
    slug: 'compress',
    tool: 'compress',
    title: 'Compress PDF Online — Free | FileForge',
    description: 'Reduce PDF file size by up to 80% without losing quality. Powered by PyMuPDF engine.',
    headline: 'Compress PDF',
    subtext: 'Dramatically shrink your PDF file size while preserving visual quality.',
    icon: '🗜️',
    color: '#10b981', // Emerald Green
  },
  {
    slug: 'protect',
    tool: 'protect',
    title: 'Protect PDF Online — Add Password | FileForge',
    description: 'Encrypt your PDF documents with AES-256 military-grade password protection. Free and secure.',
    headline: 'Protect PDF',
    subtext: 'Add a password to your PDF to prevent unauthorized viewing and editing.',
    icon: '🛡️',
    color: '#3b82f6', // Blue
  },
  {
    slug: 'unlock',
    tool: 'unlock',
    title: 'Unlock PDF Online — Remove Password | FileForge',
    description: 'Remove password protection from your PDF files permanently so they are easy to share.',
    headline: 'Unlock PDF',
    subtext: 'Provide the current password to permanently decrypt and unlock your PDF file.',
    icon: '🔓',
    color: '#8b5cf6', // Purple
  },
  {
    slug: 'redact',
    tool: 'redact',
    title: 'Redact Text in PDF — Hide Sensitive Data | FileForge',
    description: 'Permanently blackout sensitive text, names, and numbers from your PDF documents.',
    headline: 'Redact PDF',
    subtext: 'Automatically find and permanently blackout sensitive words from your entire document.',
    icon: '⬛',
    color: '#374151', // Dark Gray
  },
  {
    slug: 'sign',
    tool: 'sign',
    title: 'Sign PDF Online — Add eSignature | FileForge',
    description: 'Stamp your signature image onto your PDF documents instantly and securely.',
    headline: 'Sign PDF',
    subtext: 'Upload your document and signature image to stamp it perfectly every time.',
    icon: '✍️',
    color: '#eab308', // Yellow
  },
  {
    slug: 'compare',
    tool: 'compare',
    title: 'Compare PDFs Side-by-Side Online | FileForge',
    description: 'Visually compare two PDF documents side-by-side right in your browser.',
    headline: 'Compare PDFs',
    subtext: 'Upload two versions of a document to visually spot the differences side-by-side.',
    icon: '📖',
    color: '#0ea5e9', // Sky Blue
  },
];

// ─── AI Tools ────────────────────────────────────────────────────────

export const AI_TOOLS = [
  {
    slug: 'summarize-pdf',
    operation: 'summarize',
    acceptExt: '.pdf',
    fileType: 'PDF',
    title: 'Summarize PDF with AI — Free | FileForge',
    description: 'Upload a PDF and get an instant AI-generated summary. Powered by Llama 3.1 via LangChain.',
    headline: 'Summarize PDF with AI',
    subtext: 'Upload your PDF and let Llama 3.1 generate a professional, detailed summary in seconds.',
    icon: '📝',
  },
  {
    slug: 'summarize-txt',
    operation: 'summarize',
    acceptExt: '.txt',
    fileType: 'TXT',
    title: 'Summarize Text File with AI — Free | FileForge',
    description: 'Upload a text file and get an instant AI-generated summary. Powered by Llama 3.1.',
    headline: 'Summarize Text File with AI',
    subtext: 'Feed your text document to Llama 3.1 and receive a clear, concise summary.',
    icon: '📝',
  },
  {
    slug: 'extract-data-pdf',
    operation: 'extract',
    acceptExt: '.pdf',
    fileType: 'PDF',
    title: 'Extract Data from PDF with AI — Free | FileForge',
    description: 'Upload a PDF and let AI extract all key names, dates, organizations, and figures into a structured format.',
    headline: 'Extract Data from PDF',
    subtext: 'Let AI identify and organize every name, date, and data point in your PDF.',
    icon: '🔍',
  },
  {
    slug: 'extract-data-txt',
    operation: 'extract',
    acceptExt: '.txt',
    fileType: 'TXT',
    title: 'Extract Data from Text File with AI — Free | FileForge',
    description: 'Upload a text file and let AI extract all key information into a clean, structured format.',
    headline: 'Extract Data from Text File',
    subtext: 'Automatically pull out names, dates, and key figures from any text document.',
    icon: '🔍',
  },
];

// ─── Popular Conversions (for Homepage) ──────────────────────────────

export const POPULAR_CONVERSIONS = [
  { slug: 'pdf-to-jpg', from: 'PDF', to: 'JPG', icon: '📄' },
  { slug: 'pdf-to-docx', from: 'PDF', to: 'DOCX', icon: '📝' },
  { slug: 'jpg-to-png', from: 'JPG', to: 'PNG', icon: '🖼️' },
  { slug: 'mp4-to-mp3', from: 'MP4', to: 'MP3', icon: '🎵' },
  { slug: 'png-to-webp', from: 'PNG', to: 'WebP', icon: '⚡' },
  { slug: 'mp4-to-gif', from: 'MP4', to: 'GIF', icon: '🎬' },
  { slug: 'wav-to-mp3', from: 'WAV', to: 'MP3', icon: '🎧' },
  { slug: 'webp-to-jpg', from: 'WebP', to: 'JPG', icon: '🔄' },
];

// ─── Helper ──────────────────────────────────────────────────────────

export function getConversionBySlug(slug) {
  return CONVERSION_MAP.find((c) => c.slug === slug) || null;
}

export function getPdfToolBySlug(slug) {
  return PDF_TOOLS.find((t) => t.slug === slug) || null;
}

export function getAiToolBySlug(slug) {
  return AI_TOOLS.find((t) => t.slug === slug) || null;
}
